const allData = {
  education:[
    {id:1, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
        {id:2, title:"নিউজিল্যান্ডে উচ্চশিক্ষা: স্কলারশিপ-রোলিং ইনটেক-খণ্ডকালীন কাজের সুযোগ, আইইএলটিএসে ৬.৫ হলে আবেদন", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
    {id:3, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
    {id:4, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
     {id:5, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
  ],
  nu:[
    {id:1, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
        {id:2, title:"নিউজিল্যান্ডে উচ্চশিক্ষা: স্কলারশিপ-রোলিং ইনটেক-খণ্ডকালীন কাজের সুযোগ, আইইএলটিএসে ৬.৫ হলে আবেদন", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
    {id:3, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
    {id:4, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
     {id:5, title:"৬ষ্ঠ, ৭ম, ৮ম ও ৯ম শ্রেণির ২০২৪ শিক্ষাবর্ষের শিখনকালীন মূল্যায়ন ও বার্ষিক পরীক্ষার জরুরি নির্দেশনা", description:"", content:"", image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722159993/ecommerce_azim/q6glxh4jmt2kpypnvruj.jpg",
    },
  ],
  sport:[
    {id:1, title:"Cricket Update News", description:"", content:"", image:"https://ibb.co.com/zFBR75g"},
  ],
  international:[
    {id:1, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"Ark Invest sold 44,609 shares of its ARKB Spot Bitcoin ETF for $2.8 million as part of a rebalancing strategy. The firm retains $139.7 million in ARKB, making it the second-largest holding in ARKW. US spot Bitcoin ETFs saw $4.5 million in inflows, while Ether…", content:"", image:"https://coinjournal.net/wp-content/uploads/2023/06/1687980468533-81ee7104-74fe-4b71-a080-6a1be8b9d410.jpg"},
       {id:2, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"}, 
    {id:3, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"},
    {id:4, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"},
  {id:5, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"},
 {id:6, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"},
  {id:7, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"},
 {id:8, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"},
 {id:9, title:"Hezbollah fires missile at Tel Aviv in further escalation after heavy Israeli strikes on Lebanon Hezbollah launched a ballistic missile at Tel Aviv early Wednesday, in a further escalation after Israel carried out strikes on Lebanon that killed hundreds of people and the militants fired rockets across wider areas of northern Israel", description:"", content:"", image:"https://i.postimg.cc/vZPGHRwz/s-jaishankar-254857344-16x9-0.jpg"},
 {id:10, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://img.digitimes.com/newsshow/20240925pd200_files/1_b.jpg"},
  {id:11, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://i0.wp.com/electrek.co/wp-content/uploads/sites/3/2024/09/24SEP_UNED.jpg?resize=1200%2C628&quality=82&strip=all&ssl=1"},
    {id:12, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://techreport.com/wp-content/uploads/2023/08/cryptocurrency-gf0d55d759_1280.jpg?_t=1727225838"},
      {id:13, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://nypost.com/wp-content/uploads/sites/2/2024/09/dimon-musk.jpg?quality=75&strip=all&1727203853&w=1024"},
        {id:14, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://images.bild.de/66f288f4a8be4520e7696866/27f8059f13396c34f7efdf4640bc4a87,fd42f1eb?w=1280"},
        {id:15, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://images.bild.de/66f288f4a8be4520e7696866/27f8059f13396c34f7efdf4640bc4a87,fd42f1eb?w=1280"},
         {id:16, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://images.bild.de/66f288f4a8be4520e7696866/27f8059f13396c34f7efdf4640bc4a87,fd42f1eb?w=1280"},
            {id:17, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://images.bild.de/66f288f4a8be4520e7696866/27f8059f13396c34f7efdf4640bc4a87,fd42f1eb?w=1280"},
       {id:18, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://images.bild.de/66f288f4a8be4520e7696866/27f8059f13396c34f7efdf4640bc4a87,fd42f1eb?w=1280"},   
      {id:19, title:"Elon Musk Responds To Venture Capitalist's Claim On Government Subsidies For SpaceX, Tesla: 'Do Some Research Before You Display Your Utter Ignorance'", description:"Elon Musk had a sharp exchange of words with venture capitalist Vinod Khosla on Musk’s X platform on Saturday as Khosla brought up government support for Musk’s businesses. More Moderate Path Needed: The exchanges started several months ago with Khosla, the c…", content:"", image:"https://images.bild.de/66f288f4a8be4520e7696866/27f8059f13396c34f7efdf4640bc4a87,fd42f1eb?w=1280"},
  ],
  top:[
    {id:1, title:"Top news", description:"", content:"", image:"https://i.ibb.co.com/71J8D4h/240924-mike-johnson-donald-trump-se-1103a-19f83e.jpg"},
      {id:2, title:"ভারতে ইলিশ রপ্তানি বন্ধে ব্যবস্থা নিতে সরকারকে অনুরোধ করে আইনি নোটিশ পাঠিয়েছেন সুপ্রিম কোর্টের এক আইনজীবী।",
     image:"https://i.ibb.co.com/71J8D4h/240924-mike-johnson-donald-trump-se-1103a-19f83e.jpg",   
    description:"রোববার (২২ সেপ্টেম্বর) সুপ্রিম কোর্টের আইনজীবী মো. মাহমুদুল হাসান এই নোটিশ পাঠিয়েছেন। বাণিজ্য মন্ত্রণালয়ের সচিব, মৎস্য ও প্রাণিসম্পদ মন্ত্রণালয়ের সচিব, জাতীয় রাজস্ব বোর্ডের চেয়ারম্যান ও আমদানি-রপ্তানি কার্যালয়ের প্রধান নিয়ন্ত্রক বরাবরে এ নোটিশ পাঠানো হয়েছে।  এ ছাড়া আইনি নোটিশে পাওয়ার তিন দিনের মধ্যে ভারতে ইলিশ রপ্তানি বন্ধে প্রয়োজনীয় ব্যবস্থা নিতে নোটিশে অনুরোধ করা হয়েছে। অন্যথায় এ বিষয়ে ব্যবস্থা নিতে হাইকোর্টে রিট পিটিশন দায়ের করা হবে বলে জানিয়েছেন আইনজীবী।আইনি নোটিশে বলা হয়, ভারতের বিশাল ও বিস্তৃত সমুদ্র সীমা রয়েছে। ভারতের জলসীমায় ব্যাপকভাবে ইলিশ উৎপাদন হয়। এই বিবেচনায় বাংলাদেশ থেকে ভারতের ইলিশ মাছ আমদানির কোনো প্রয়োজন নেই। কিন্তু ভারত মূলত বাংলাদেশের পদ্মা নদীর ইলিশ আমদানি করে থাকে। বাংলাদেশে ভারতীয় এজেন্ট ও মাছ রপ্তানিকারকরা সারা বছর পদ্মা নদীর ইলিশ মাছ মজুদ করে রাখে এবং বাংলাদেশ সরকারের অনুমতি সাপেক্ষে পদ্মা নদীর ইলিশ ভারতে রপ্তানি করে এবং ক্ষেত্রবিশেষে সীমান্ত দিয়ে অবৈধভাবে পাচার করে। ফলে দেশের জনগণ বাজারে গিয়ে পদ্মার ইলিশ পায় না।আরও বলা হয়, পদ্মা নদীতে যে সীমিত পরিমাণ ইলিশ পাওয়া যায়, তা দেশের মানুষের চাহিদা অনুযায়ী যথেষ্ট নয়। এই অবস্থায় যদি পদ্মার সব ইলিশ ভারতে চলে যায় তাহলে বাংলাদেশের জনগণ পদ্মার ইলিশ খেতে পারবে না। এভাবে বাংলাদেশের জনগণকে পদ্মার ইলিশ থেকে বঞ্চিত করে ভারতের জনগণকে পদ্মার ইলিশ খাওয়ানো বাংলাদেশের সরকারের জন্য সমীচীন নয়। এ কথা সত্য যে, বাংলাদেশ নিত্যপ্রয়োজনীয় বিভিন্ন জিনিস ভারত থেকে আমদানি করে কিন্তু ভারত সরকার কখনোই তার নিজের দেশের জনগণের চাহিদা না মিটিয়ে বাংলাদেশে রপ্তানি করে না।এদিকে শনিবার (২১ সেপ্টেম্বর) এক বিজ্ঞপ্তিতে বাণিজ্য মন্ত্রণালয় জানিয়েছে, আসন্ন দুর্গাপূজা উপলক্ষে বিভিন্ন রপ্তানিকারকদের আবেদনের প্রেক্ষিতে নির্ধারিত শর্তাবলি পূরণসাপেক্ষে ৩ হাজার টন ইলিশ রপ্তানির অনুমোদন দেওয়া হয়েছে। সংশ্লিষ্ট আবেদনকারীদের প্রয়োজনীয় কাগজপত্রসহ আগামী ২৪ সেপ্টেম্বর দুপুর ১২টার মধ্যে বাণিজ্য মন্ত্রণালয় বরাবর (উপ-সচিব, রপ্তানি-২ শাখা, কক্ষ নম্বর ১২৭, ভবন নম্বর ৩, বাণিজ্য মন্ত্রণালয়, বাংলাদেশ সচিবালয়) আবেদন করার জন্য অনুরোধ করা হয়।তবে উল্লিখিত সময়সীমার পর প্রাপ্ত আবেদন গ্রহণযোগ্য হবে না। এ ছাড়া যারা এরই মধ্যে আবেদন করেছেন তাদের নতুন করে আবেদনের প্রয়োজন নেই বলেও জানিয়েছে বাণিজ্য মন্ত্রণালয়।মাহমুদুল হাসান জানান, বাংলাদেশের রপ্তানি নীতি ২০২১-২৪ অনুযায়ী ইলিশ মাছ মুক্তভাবে রপ্তানিযোগ্য কোনো মাছ নয়। এ পরিস্থিতিতে বাণিজ্য মন্ত্রণালয় ভারতে ইলিশ মাছ রপ্তানির অনুমতি দিয়ে বাংলাদেশের জনগণের স্বার্থবিরোধী কাজ"
      , content:"hello"},
          {id:3, title:"Top news", description:"", content:"", image:"https://i.ibb.co.com/71J8D4h/240924-mike-johnson-donald-trump-se-1103a-19f83e.jpg"},
      {id:4, title:"ভারতে ইলিশ রপ্তানি বন্ধে ব্যবস্থা নিতে সরকারকে অনুরোধ করে আইনি নোটিশ পাঠিয়েছেন সুপ্রিম কোর্টের এক আইনজীবী।",
     image:"https://res.cloudinary.com/dmmnpv81y/image/upload/v1722408280/ecommerce_azim/dparktnhzlw6fgfwibni.jpg",   
    description:"রোববার (২২ সেপ্টেম্বর) সুপ্রিম কোর্টের আইনজীবী মো. মাহমুদুল হাসান এই নোটিশ পাঠিয়েছেন। বাণিজ্য মন্ত্রণালয়ের সচিব, মৎস্য ও প্রাণিসম্পদ মন্ত্রণালয়ের সচিব, জাতীয় রাজস্ব বোর্ডের চেয়ারম্যান ও আমদানি-রপ্তানি কার্যালয়ের প্রধান নিয়ন্ত্রক বরাবরে এ নোটিশ পাঠানো হয়েছে।  এ ছাড়া আইনি নোটিশে পাওয়ার তিন দিনের মধ্যে ভারতে ইলিশ রপ্তানি বন্ধে প্রয়োজনীয় ব্যবস্থা নিতে নোটিশে অনুরোধ করা হয়েছে। অন্যথায় এ বিষয়ে ব্যবস্থা নিতে হাইকোর্টে রিট পিটিশন দায়ের করা হবে বলে জানিয়েছেন আইনজীবী।আইনি নোটিশে বলা হয়, ভারতের বিশাল ও বিস্তৃত সমুদ্র সীমা রয়েছে। ভারতের জলসীমায় ব্যাপকভাবে ইলিশ উৎপাদন হয়। এই বিবেচনায় বাংলাদেশ থেকে ভারতের ইলিশ মাছ আমদানির কোনো প্রয়োজন নেই। কিন্তু ভারত মূলত বাংলাদেশের পদ্মা নদীর ইলিশ আমদানি করে থাকে। বাংলাদেশে ভারতীয় এজেন্ট ও মাছ রপ্তানিকারকরা সারা বছর পদ্মা নদীর ইলিশ মাছ মজুদ করে রাখে এবং বাংলাদেশ সরকারের অনুমতি সাপেক্ষে পদ্মা নদীর ইলিশ ভারতে রপ্তানি করে এবং ক্ষেত্রবিশেষে সীমান্ত দিয়ে অবৈধভাবে পাচার করে। ফলে দেশের জনগণ বাজারে গিয়ে পদ্মার ইলিশ পায় না।আরও বলা হয়, পদ্মা নদীতে যে সীমিত পরিমাণ ইলিশ পাওয়া যায়, তা দেশের মানুষের চাহিদা অনুযায়ী যথেষ্ট নয়। এই অবস্থায় যদি পদ্মার সব ইলিশ ভারতে চলে যায় তাহলে বাংলাদেশের জনগণ পদ্মার ইলিশ খেতে পারবে না। এভাবে বাংলাদেশের জনগণকে পদ্মার ইলিশ থেকে বঞ্চিত করে ভারতের জনগণকে পদ্মার ইলিশ খাওয়ানো বাংলাদেশের সরকারের জন্য সমীচীন নয়। এ কথা সত্য যে, বাংলাদেশ নিত্যপ্রয়োজনীয় বিভিন্ন জিনিস ভারত থেকে আমদানি করে কিন্তু ভারত সরকার কখনোই তার নিজের দেশের জনগণের চাহিদা না মিটিয়ে বাংলাদেশে রপ্তানি করে না।এদিকে শনিবার (২১ সেপ্টেম্বর) এক বিজ্ঞপ্তিতে বাণিজ্য মন্ত্রণালয় জানিয়েছে, আসন্ন দুর্গাপূজা উপলক্ষে বিভিন্ন রপ্তানিকারকদের আবেদনের প্রেক্ষিতে নির্ধারিত শর্তাবলি পূরণসাপেক্ষে ৩ হাজার টন ইলিশ রপ্তানির অনুমোদন দেওয়া হয়েছে। সংশ্লিষ্ট আবেদনকারীদের প্রয়োজনীয় কাগজপত্রসহ আগামী ২৪ সেপ্টেম্বর দুপুর ১২টার মধ্যে বাণিজ্য মন্ত্রণালয় বরাবর (উপ-সচিব, রপ্তানি-২ শাখা, কক্ষ নম্বর ১২৭, ভবন নম্বর ৩, বাণিজ্য মন্ত্রণালয়, বাংলাদেশ সচিবালয়) আবেদন করার জন্য অনুরোধ করা হয়।তবে উল্লিখিত সময়সীমার পর প্রাপ্ত আবেদন গ্রহণযোগ্য হবে না। এ ছাড়া যারা এরই মধ্যে আবেদন করেছেন তাদের নতুন করে আবেদনের প্রয়োজন নেই বলেও জানিয়েছে বাণিজ্য মন্ত্রণালয়।মাহমুদুল হাসান জানান, বাংলাদেশের রপ্তানি নীতি ২০২১-২৪ অনুযায়ী ইলিশ মাছ মুক্তভাবে রপ্তানিযোগ্য কোনো মাছ নয়। এ পরিস্থিতিতে বাণিজ্য মন্ত্রণালয় ভারতে ইলিশ মাছ রপ্তানির অনুমতি দিয়ে বাংলাদেশের জনগণের স্বার্থবিরোধী কাজ"
      , content:""},
      
  ],
  job:{
  Dhaka:[
    {id:1, title:"", description:"", content:"", image:""},
    {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  Barishal:[
    {id:1, title:"", description:"", content:"", image:""},
        {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  Khulna:[
    {id:1, title:"", description:"", content:"", image:""},
        {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  Sylhet:[
    {id:1, title:"", description:"", content:"", image:""},
        {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  Chattogram:[
    {id:1, title:"", description:"", content:"", image:""},
      {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  Rajshahi:[
    {id:1, title:"", description:"", content:"", image:""},
        {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  Rangpur:[
    {id:1, title:"", description:"", content:"", image:""},
        {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  Mymenshingh:[
    {id:1, title:"", description:"", content:"", image:""},
      {id:2, title:"", description:"", content:"", image:""},
     {id:3, title:"", description:"", content:"", image:""},
   {id:4, title:"", description:"", content:"", image:""},
    {id:5, title:"", description:"", content:"", image:""},
     {id:6, title:"", description:"", content:"", image:""},
   {id:7, title:"", description:"", content:"", image:""},
    {id:8, title:"", description:"", content:"", image:""},
    {id:9, title:"", description:"", content:"", image:""},
  ],
  hotjob:[{id:1, title:"", description:"", content:"", image:""}],
  },
};
export const getAllData = ()=>{
  return allData;
};